using System.ComponentModel.DataAnnotations;

namespace Airline_Ticketing.DTOs.Request
{
    public class CreateTicketRequest
    {
        [Required(ErrorMessage = "Booking ID is required.")]
        public int BookingID { get; set; }

        [Required(ErrorMessage = "BPID is required.")]
        public int BPID { get; set; }

        [Required(ErrorMessage = "Flight ID is required.")]
        public int FlightID { get; set; }

        // TicketNumber will be auto-generated in the service
        // IssueDate will be set to DateTime.Now in the service
        // Status will be set to default value in the service
        // TicketID is auto-generated by the database
    }
}
